# Generated by Django 2.2.5 on 2021-07-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='First name of the student')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last name of the student')),
                ('hometown', models.CharField(max_length=32, verbose_name='Home town')),
                ('age', models.IntegerField(verbose_name='Age of the student')),
            ],
        ),
    ]
