# Generated by Django 2.2.5 on 2021-07-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='linkedin_profile',
            field=models.CharField(default='https://www.linkedin.com/', max_length=256, verbose_name='LinkedIn profile link'),
        ),
    ]
