# Generated by Django 2.2.5 on 2021-07-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_linkedin_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title of the course')),
                ('instructor', models.CharField(max_length=32, verbose_name='Instructor of the course')),
                ('student', models.ManyToManyField(to='student.Student')),
            ],
        ),
    ]
